spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

indexer:
  rpc:
    primary: ${ALCHEMY_URL}
    fallback: ${INFURA_URL}
  confirmations: 12
  reconcile:
    lookback: 100
alchemy:
  host: worldchain-sepolia.g.alchemy.com
  apiKey: ${ALCHEMY_API_KEY}